configuration:
  managedByConfigPod:
    enabled: true
    syncUrl: ""
  mongodb:
    name: free5gc
    url: mongodb://relation-117:WKu41vhksRAIipwAb3XZThofkIXQmzYa@mongodb-0.mongodb-endpoints:27017/free5gc?replicaSet=mongodb&authSource=admin
    authKeysDbName: authentication
    authUrl: mongodb://relation-118:WOhBfSjJrIZVv3PmmE5SBqezYct2CTnC@mongodb-0.mongodb-endpoints:27017/authentication?replicaSet=mongodb&authSource=admin
    webuiDbName: webui
    webuiDbUrl: mongodb://relation-116:8xO84US2L5XwjFGIzA2ngBr6zKp37y2w@mongodb-0.mongodb-endpoints:27017/webui?replicaSet=mongodb&authSource=admin
  spec-compliant-sdf: false
  enableAuthentication: false
info:
  description: WebUI initial local configuration
  version: 1.0.0
  http-version: 2
logger:
  WEBUI:
    debugLevel: info