name: Release v1.0.0 scheduled CI

on:
  schedule:
    - cron: "0 6 * * 0"

jobs:
  codeql:
    uses: ./.github/workflows/codeql-analysis.yaml
    with:
      branch-name: "v1.0.0"

  nms-lint-report:
    uses: ./.github/workflows/nms-lint-report.yaml
    with:
      branch-name: "v1.0.0"

  build-nms:
    needs: nms-lint-report
    uses: ./.github/workflows/build-nms.yaml
    with:
      branch-name: "v1.0.0"

  build-rock:
    needs: build-nms
    uses: canonical/sdcore-github-workflows/.github/workflows/build-rock.yaml@v2.3.1
    with:
      branch-name: "v1.0.0"

  scan-rock:
    needs: build-rock
    uses: canonical/sdcore-github-workflows/.github/workflows/scan-rock.yaml@v2.3.1
    with:
      branch-name: "v1.0.0"
