name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install skopeo
        run: |
          sudo snap install --devmode --channel edge skopeo
      - name: Install yq
        run: |
          sudo snap install yq
      - uses: actions/download-artifact@v4
        with:
          name: rock

      - name: Import
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          echo "image_name=${image_name}" >> $GITHUB_ENV
          version="$(yq '.version' rockcraft.yaml)"
          echo "version=${version}" >> $GITHUB_ENV
          rock_file=$(ls *.rock | tail -n 1)
          sudo skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/canonical/${image_name}:${version}"

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/canonical/${{env.image_name}}:${{env.version}}"
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      - name: Push to github package
        run: |
          docker push ghcr.io/canonical/${{env.image_name}}:${{env.version}}
